version: '3'

services:
  app-nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./build/nginx/Dockerfile
    depends_on:
      - app-php
    volumes:
      - ./:/var/www/html:cached
    environment:
      - PHP_FPM_HOST=app-php
      - PHP_FPM_PORT=9000
    ports:
      - ${APP_PORT}:80
    networks:
      - app-network
  app-php:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./build/php/Dockerfile
    depends_on:
      - app-database
      - app-redis
    volumes:
      - ./:/var/www/html:cached
    networks:
      - app-network
  app-database:
    restart: unless-stopped
    image: mariadb:10.4
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - ${MYSQL_LOCAL_PORT}:3306
    networks:
      - app-network
  app-redis:
    restart: unless-stopped
    image: redis:5
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  database-data:
  redis-data:

networks:
  app-network:
    driver: bridge

