version: '3'

services:
  app-nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./build/nginx/Dockerfile
    depends_on:
      - app-php
    volumes:
      - ./:/var/www/html:cached
    environment:
      - PHP_FPM_HOST=app-php
      - PHP_FPM_PORT=9000
    ports:
      - ${APP_PORT}:80
    networks:
      - app-network
  app-php:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./build/php/Dockerfile
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/var/www/html:cached
    networks:
      - app-network
  mysql:
    restart: unless-stopped
    image: mariadb:10.4
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - ${DB_LOCAL_PORT}:3306
    networks:
      - app-network
  redis:
    restart: unless-stopped
    image: redis:5
    volumes:
      - redis:/data
    networks:
      - app-network

volumes:
  mysql:
  redis:

networks:
  app-network:
    driver: bridge

